version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

